USE ProjectTrackingDB;

INSERT INTO Users VALUES (0, 'rstack', md5('rstack:timekeeping:doofus'), 'Ryan Stack', 1, false, Now(), Now() );
INSERT INTO Users VALUES (0, 'ktuttle', md5('ktuttle:timekeeping:doofus'), 'Karen Tuttle', 1, false, Now(), Now() );
INSERT INTO Users VALUES (0, 'jwebb', md5('jwebb:timekeeping:doofus'), 'Jared Webb', 1, false, Now(), Now() );
INSERT INTO Users VALUES (0, 'kwakevainen', md5('kwakevainen:timekeeping:doofus'), 'Katie Wakevainen', 1, false, Now(), Now() );
INSERT INTO Users VALUES (0, 'manager', md5('manager:timekeeping:doofus'), 'manager', 1, false, Now(), Now() );
INSERT INTO Users VALUES (0, 'user', md5('user:timekeeping:doofus'), 'user', 1, false, Now(), Now() );

INSERT INTO Roles VALUES ((Select UserID from Users where Username='rstack'), 'ADMINISTRATOR', Now(), Now() );
INSERT INTO Roles VALUES ((Select UserID from Users where Username='ktuttle'), 'ADMINISTRATOR', Now(), Now() );
INSERT INTO Roles VALUES ((Select UserID from Users where Username='jwebb'), 'ADMINISTRATOR', Now(), Now() );
INSERT INTO Roles VALUES ((Select UserID from Users where Username='kwakevainen'), 'ADMINISTRATOR', Now(), Now() );
INSERT INTO Roles VALUES ((Select UserID from Users where Username='manager'), 'MANAGER', Now(), Now() );
INSERT INTO Roles VALUES ((Select UserID from Users where Username='user'), 'USER', Now(), Now() );

INSERT INTO PROJECTS (PROJECT_NAME, START_DATE, END_DATE, PROJECT_MANAGER_ID, IS_ACTIVE) VALUES ("Project 1",NOW(),NOW(),1,TRUE);
INSERT INTO PROJECTS (PROJECT_NAME, START_DATE, END_DATE, PROJECT_MANAGER_ID, IS_ACTIVE) VALUES ("Project 2",NOW(),NOW(),1,TRUE);
INSERT INTO PROJECTS (PROJECT_NAME, START_DATE, END_DATE, PROJECT_MANAGER_ID, IS_ACTIVE) VALUES ("Project 3",NOW(),NOW(),2,TRUE);
INSERT INTO PROJECTS (PROJECT_NAME, START_DATE, END_DATE, PROJECT_MANAGER_ID, IS_ACTIVE) VALUES ("Project 4",NOW(),NOW(),2,TRUE);
INSERT INTO PROJECTS (PROJECT_NAME, START_DATE, END_DATE, PROJECT_MANAGER_ID, IS_ACTIVE) VALUES ("Project 5",NOW(),NOW(),1,FALSE);
INSERT INTO PROJECTS (PROJECT_NAME, START_DATE, END_DATE, PROJECT_MANAGER_ID, IS_ACTIVE) VALUES ("Project 6",NOW(),NOW(),2,TRUE);
INSERT INTO PROJECTS (PROJECT_NAME, START_DATE, END_DATE, PROJECT_MANAGER_ID, IS_ACTIVE) VALUES ("Project 7",NOW(),NOW(),2,TRUE);

INSERT INTO PROJECT_ASSIGNMENT (PROJECT_ID,UserID,PRIMARY_CONTRIBUTOR) VALUES (1,1,TRUE);
INSERT INTO PROJECT_ASSIGNMENT (PROJECT_ID,UserID,PRIMARY_CONTRIBUTOR) VALUES (2,1,TRUE);
INSERT INTO PROJECT_ASSIGNMENT (PROJECT_ID,UserID,PRIMARY_CONTRIBUTOR) VALUES (3,2,TRUE);
INSERT INTO PROJECT_ASSIGNMENT (PROJECT_ID,UserID,PRIMARY_CONTRIBUTOR) VALUES (4,2,TRUE);
INSERT INTO PROJECT_ASSIGNMENT (PROJECT_ID,UserID,PRIMARY_CONTRIBUTOR) VALUES (1,2,TRUE);
INSERT INTO PROJECT_ASSIGNMENT (PROJECT_ID,UserID,PRIMARY_CONTRIBUTOR) VALUES (1,6,TRUE);

INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (1,1,86,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',TRUE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (2,1,13,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',TRUE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (3,1,1,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',FALSE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (3,2,50,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',TRUE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (4,2,50,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',TRUE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (3,1,86,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',FALSE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (4,1,2,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',FALSE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (6,1,8,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',FALSE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (7,1,4,"Didnt play enough ping pong","Play more ping pong","Work less","Won in roundies",'PARTIAL',FALSE,"",'GREEN',NOW());
INSERT INTO PROJECT_ENTRIES (PROJECT_ID,UserID,EFFORT,ISSUES,UPCOMING_GOALS,PREVIOUS_GOALS,ACCOMPLISHMENTS,ENTRY_STATE,IS_SUMMARY,MISC,HEALTH,ENTRY_DATE) VALUES (1,6,100,"stuff","f","g","a",'PARTIAL',FALSE,"",NULL,NOW());